### ISSUE TITLE
В 2017 году два животных

### ISSUE THREAD

**Issue by code-exchange** [AHandless/ChineseCalendar#1]
Посмотрел у тебя эту программу. Сам делал такую на C++/Qt. Когда я её делал, я всё это разбирал и понял, что там самое сложное далеко не в иероглифах. Фишка в том, что в январе 2017-го года будет обезьяна ещё, а в марте уже будет петух. То есть это два животных, две стихии и так далее в одном году.

**Comment by AHandless** [comment]
Спасибо за интересный комментарий, но вряд ли я буду что-либо делать для разрешения этого ишью, так как писал эту программку как хеллоуворлд.Не ожидал, что кто-нибудь сюда когда-нибудь заглянет.

**Comment by code-exchange** [comment]
> Не ожидал, что кто-нибудь сюда когда-нибудь заглянет.

Я пришёл через резюме на trudvsem. Интересно было просто, кто у нас программирует. В нотах я не разбираюсь, алгоритм парсера не могу оценить, а в этом не мог удержаться, потому что это, видимо, все пишут на первых этапах и у каждого свой вариант получается. Они по сложности разные могут быть, поэтому уровень можно оценить довольно точно.
Это вот моя прога
http://pixs.ru/showimage/yearinfo1p_1151327_27661538.png
http://pixs.ru/showimage/yearinfo2p_9308653_27661544.png
Короче, она на миллион лет до нашей эры смотрит и на миллион лет нашей эры. То есть год рождения Архимеда какого-нибудь посмотреть - запросто.

**Comment by AHandless** [comment]
Понятно. Неплохая программа у вас вышла. А моё резюме на trudvsem уже, увы, неактуально.
> Интересно было просто, кто у нас программирует. 
«У нас» это вы имели в виду на Сахалине, если не секрет?

**Comment by code-exchange** [comment]
> «У нас» это вы имели в виду на Сахалине, если не секрет?

Ну да, смотрел резюме, но у всех обычно только слова, репозиториев нет ни у кого. Написать-то можно что угодно, что мол всё знаю и всё могу. Другое дело - код свой показать. А тут увидел репозиторий, пошёл посмотреть на код.

> Понятно. Неплохая программа у вас вышла.

Да я её даже не выкладывал, просто в систему себе поставил и где-то раза три в месяц обращаюсь к ней за инфой. Там нет документации и лицензии, а без документации проги не выкладываю, потому что как-то некрасиво смотрится. Внешний вид-то там несложно было сделать, так как это просто формошлёпство в дизайнере. Все сложности были алгоритме (там несколько ветвей вычисления года, 200 лет из википедии взял напрямую), потому что лунный год не так просто вычислить, даты постоянно меняются. А ещё сложно было картинки все сделать. Чтобы год козы сделать, скачал, наверное, сотню коз и потом выбирал из них самую красивую и вырезал её потом в Gimp'е. Ну я просто делал это всё, чтобы понять, сколько времени уйдёт на изготовление полной программы со всеми картинками. На код ушло немного времени, процентов 30 может. Остальное всё ушло на исследования разных календарных вопросов и изготовление картинок.
